server:
  port: 8080
#H2 Settings
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test:AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: none
    show-sql: true
