server:
  port: 8080
#H2 Settings
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test:AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: update
    show-sql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8

springdoc:
  version: '@project.version'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/v1/**
    - /test/**
    - /v1/**
